pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  MajorVersion: 1
  MinorVersion: 0
  Patch: 0
  System.Debug: 'false'
  AssemblyVersion: ''

name: $(MajorVersion).$(MinorVersion).$(Patch)+$(Rev:r)

steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core SDK 2.2.104'
    inputs:
      version: 2.2.104

  - task: DotNetCoreCLI@2
    displayName: 'Dotnet Restore'
    inputs:
      command: restore
      projects: '**/*.csproj'
      vstsFeed: '347da6e2-9f2f-4133-8f52-8e0d1d2474e2'

  - task: DotNetCoreCLI@2
    displayName: 'Dotnet Build'
    inputs:
      projects: '**/*.csproj'
      arguments: '--configuration $(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Dotnet Test'
    inputs:
      command: test
      projects: '**/*[Tt]ests/*.csproj'
      arguments: '--configuration $(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Dotnet Publish'
    inputs:
      command: publish
      projects: '**/*Flow.csproj'
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
      zipAfterPublish: True
      publishWebProjects: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
